import { useLayoutEffect, useRef, useState } from "react";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { EASE, DURATION } from "../../lib/motion";
import appIcon from "../../assets/images/recallguard-icon.png";

gsap.registerPlugin(ScrollTrigger);

// iPhone logical points. Everything inside the screen is authored against this
// box and then scaled to whatever width the layout gives us, which is the same
// trick the archived marketing mockups used — it keeps the notification's type
// at true iOS proportions instead of guessing at a smaller size.
//
// SCREEN is the glass. BEZEL is the black band around it. The outer element has
// to be SCREEN + 2*BEZEL, because border-box padding would otherwise eat the
// bezel out of the screen and leave 370pt of glass holding 390pt of UI — which
// is exactly how the notification ended up hanging over the right edge.
const SCREEN_WIDTH = 390;
const SCREEN_HEIGHT = 844;
const BEZEL = 10;
const LOGICAL_WIDTH = SCREEN_WIDTH + BEZEL * 2;
const LOGICAL_HEIGHT = SCREEN_HEIGHT + BEZEL * 2;

/**
 * The recall this depicts is real and is the same one the case study further
 * down the page already tells in prose: Nate's Fine Foods pre-cooked pasta,
 * sold as prepared chicken fettuccine alfredo under Walmart's Marketside label,
 * recalled June 17 2025 for Listeria monocytogenes. Reusing that recall here is
 * deliberate — the alert, the case study, and the outbreak toll then describe
 * one event instead of three unrelated exhibits.
 *
 * The archived mockup at overnight-output-archive/2026-06-10/phone-mockups used
 * an invented recall (Midwest Beef Co., FDA number F-1482-2026). Fine on a
 * social card, not on the product page — a reader cannot tell an invented brand
 * from a real one, which is the whole reason CREDITS.md bans legible brands on
 * the photography.
 *
 * Title and body are generated by the template in the app's own push builder,
 * supabase/functions/_shared/notify.ts:
 *   title = `${severityLabel}: ${brand} ${product}`
 *   body  = `${hazard}. ${brand}. Tap for details.`   (hazard path)
 * Do not hand-write a nicer sentence here. The point of the section is that
 * this is what actually lands on the lock screen.
 */
const PUSH = {
  title: "Serious risk: Marketside Chicken Fettuccine Alfredo",
  body: "Listeria monocytogenes. Nate's Fine Foods. Tap for details.",
  // The date the FDA notice published, and it really was a Tuesday.
  date: "Tuesday, June 17",
  time: "9:41",
};

export const LockScreenPhone = () => {
  const frameRef = useRef(null);
  const notifRef = useRef(null);
  const [scale, setScale] = useState(1);

  // The screen is a fixed-ratio drawing, so rather than re-expressing every
  // inner dimension in relative units we measure the slot the layout gave us
  // and scale the whole 390pt box into it. A ResizeObserver rather than a
  // resize listener: this also fires when the grid column changes width
  // without the window changing size.
  useLayoutEffect(() => {
    const frame = frameRef.current;
    if (!frame) return;

    const fit = () => setScale(frame.clientWidth / LOGICAL_WIDTH);
    fit();

    const observer = new ResizeObserver(fit);
    observer.observe(frame);
    return () => observer.disconnect();
  }, []);

  // The notification arrives as you reach the section. This is the cheap
  // equivalent of the scroll-scrubbed demo video on Scout's page: the reader
  // controls when the moment happens, so they cannot scroll past it having
  // seen only a static picture of an alert that was always there.
  useGSAP(
    () => {
      const notif = notifRef.current;
      if (!notif) return;

      // Matches the gate in usePageEntrance — the CSS reduced-motion block in
      // index.css only neutralises CSS transitions, not GSAP timelines.
      const prefersReducedMotion = window.matchMedia(
        "(prefers-reduced-motion: reduce)",
      ).matches;
      if (prefersReducedMotion) return;

      gsap.fromTo(
        notif,
        { opacity: 0, y: 18, scale: 0.97 },
        {
          opacity: 1,
          y: 0,
          scale: 1,
          duration: DURATION.base,
          ease: EASE,
          scrollTrigger: {
            trigger: frameRef.current,
            start: "top 70%",
            once: true,
          },
        },
      );
    },
    { scope: frameRef },
  );

  return (
    <div
      ref={frameRef}
      // overflow-hidden matters more than it looks: `transform: scale()` shrinks
      // what you see but leaves the layout box at its full 390pt width, so
      // without this the phone contributes a 390px-wide box to a 300px slot.
      // index.css hides the resulting document overflow, which would have made
      // this invisible here and a real clipping bug on some narrow phone later.
      className="mx-auto w-full max-w-[300px] overflow-hidden"
      // Reserve the scaled height so the section doesn't reflow once the
      // measurement lands on first paint.
      style={{ height: LOGICAL_HEIGHT * scale }}
    >
      <div
        // A depiction of the app's own output rather than a real screenshot,
        // said out loud for anyone who can't see it.
        role="img"
        aria-label={`An iPhone lock screen at ${PUSH.time} on ${PUSH.date}, showing a RecallGuard notification reading: ${PUSH.title}. ${PUSH.body}`}
        className="relative overflow-hidden rounded-[3.25rem] bg-[#0b0f1a] shadow-[0_28px_60px_-30px_rgba(26,25,23,0.55)]"
        style={{
          width: LOGICAL_WIDTH,
          height: LOGICAL_HEIGHT,
          padding: BEZEL,
          transform: `scale(${scale})`,
          transformOrigin: "0 0",
        }}
      >
        {/* Wallpaper. Kept as a deep neutral-blue field rather than a photo:
            a photographic wallpaper reads as someone's actual phone and pulls
            attention off the one thing in the frame that matters. */}
        <div className="relative h-full w-full overflow-hidden rounded-[2.75rem] bg-[radial-gradient(120%_70%_at_30%_12%,rgba(96,165,250,0.45)_0%,rgba(96,165,250,0)_60%),radial-gradient(110%_80%_at_85%_85%,rgba(30,58,138,0.9)_0%,rgba(30,58,138,0)_70%),linear-gradient(160deg,#16234f_0%,#1e3a8a_45%,#0f1733_100%)]">
          {/* Everything inside the glass renders in the Apple system stack,
              not the site's Inter. The page sets Inter on :root and the phone
              was quietly inheriting it, which is the single biggest reason this
              read as a drawing: SF Pro's digits are distinctive, and at 88px
              the clock announces the substitution before you consciously notice
              anything else. On macOS and iOS this resolves to the real SF Pro;
              elsewhere it falls back to whatever that platform calls its system
              face, which is the honest best available. */}
          <div
            aria-hidden="true"
            className="text-white"
            style={{
              fontFamily:
                '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", "Helvetica Neue", Helvetica, Arial, sans-serif',
            }}
          >
            {/* Dynamic island */}
            <div className="absolute left-1/2 top-3 h-[37px] w-[126px] -translate-x-1/2 rounded-full bg-black" />

            {/* Status bar, right side only. On the lock screen iOS leaves the
                left half empty — the time has moved to the big clock — and
                keeps signal, wifi and battery at the right. Their absence was
                one of the things making this read as a drawing. */}
            <div className="absolute right-[20px] top-[20px] flex items-center gap-[5px]">
              {/* Signal, four bars rising */}
              <span className="flex items-end gap-[2px]">
                {[4, 6, 8, 10].map((h) => (
                  <span
                    key={h}
                    style={{ height: h }}
                    className="w-[3px] rounded-[1px] bg-white"
                  />
                ))}
              </span>
              {/* Wifi, three arcs and a dot */}
              <svg width="16" height="12" viewBox="0 0 16 12" fill="none">
                <path
                  d="M1 4.2a10.5 10.5 0 0 1 14 0"
                  stroke="white"
                  strokeWidth="1.7"
                  strokeLinecap="round"
                />
                <path
                  d="M3.6 6.9a6.8 6.8 0 0 1 8.8 0"
                  stroke="white"
                  strokeWidth="1.7"
                  strokeLinecap="round"
                />
                <path
                  d="M6.3 9.5a2.9 2.9 0 0 1 3.4 0"
                  stroke="white"
                  strokeWidth="1.7"
                  strokeLinecap="round"
                />
              </svg>
              {/* Battery, capsule plus terminal nub */}
              <span className="relative flex h-[12px] w-[25px] items-center rounded-[3.5px] border border-white/45 px-[1.5px]">
                <span className="h-[8px] w-[15px] rounded-[2px] bg-white" />
                <span className="absolute -right-[3px] h-[4px] w-[1.5px] rounded-r-sm bg-white/45" />
              </span>
            </div>

            {/* Lock glyph */}
            <div className="absolute left-1/2 top-[66px] h-4 w-[22px] -translate-x-1/2 rounded border-[2.5px] border-white/90">
              <span className="absolute -top-[9px] left-[3.5px] h-[10px] w-[10px] rounded-t-md border-[2.5px] border-b-0 border-white/90" />
            </div>

            <p className="absolute top-[96px] w-full text-center text-xl font-semibold text-white/90">
              {PUSH.date}
            </p>
            <p className="absolute top-[116px] w-full text-center text-[88px] font-extralight leading-none tracking-[-2px] text-white/95">
              {PUSH.time}
            </p>

            {/* The notification. iOS clips the title to two lines and the body
                to one at this width, and so does this — a lock screen that
                shows the whole string would overstate how much of it a person
                actually reads. */}
            <div
              ref={notifRef}
              // Inset from both edges rather than a fixed width. iOS lays the
              // card out as a 14pt inset, and expressing it that way means the
              // card cannot outgrow the glass again if the screen size ever
              // changes.
              // Anchored to the BOTTOM, above the flashlight and camera row.
              // This sat at top-[280px], floating in the upper middle, which is
              // where lock screen notifications lived before iOS 16. They stack
              // up from the bottom now, and putting it back there is the single
              // biggest thing that stops the frame reading as a drawing of a
              // phone rather than a phone.
              // Material, not a flat panel. iOS notifications are a heavily
              // blurred translucent layer that picks up the wallpaper behind
              // them; this was 90% opaque over a 4px blur, which is a light
              // grey card sitting on top of a phone rather than part of it.
              // The saturate is what stops the blur going muddy.
              className="absolute inset-x-[14px] bottom-[124px] flex items-start gap-[11px] rounded-[22px] bg-white/70 p-[13px] shadow-[0_8px_24px_rgba(2,6,23,0.18)] [backdrop-filter:blur(20px)_saturate(180%)]"
            >
              <img
                src={appIcon}
                alt=""
                width="38"
                height="38"
                loading="lazy"
                className="h-[38px] w-[38px] flex-none rounded-[9px]"
              />
              <div className="min-w-0 flex-1">
                <p className="line-clamp-2 text-[14.5px] font-bold leading-[1.3] text-[#111827]">
                  {PUSH.title}
                </p>
                {/* Two lines, not one. iOS gives a collapsed notification
                    about four lines total, and a single truncated line cut
                    "Nate's Fine Foods" mid-word, which reads as a layout bug
                    rather than as the platform clipping a long string. */}
                <p className="mt-px line-clamp-2 text-[14.5px] leading-[1.32] text-[#1f2937]">
                  {PUSH.body}
                </p>
              </div>
              <span className="flex-none pl-2 text-[12.5px] leading-[1.3] text-[#6b7280]">
                now
              </span>
            </div>

            {/* Flashlight and camera. These were empty circles, which read as
                two stray dots rather than as controls — the glyph is the whole
                reason the shape is recognisable. Both are SF Symbols shapes
                approximated in SVG at iOS's own ~22pt size inside a 50pt
                translucent circle. */}
            <div className="absolute bottom-[52px] left-[38px] flex h-[50px] w-[50px] items-center justify-center rounded-full bg-black/30 backdrop-blur-sm">
              {/* Flashlight: tapered head over a body, as in flashlight.off.fill */}
              <svg width="22" height="22" viewBox="0 0 22 22" fill="none">
                <path
                  d="M7.6 3.2h6.8a1 1 0 0 1 1 1.15l-.42 2.6a1.6 1.6 0 0 1-.62 1.03l-.9.68a1.2 1.2 0 0 0-.48.96v8.03a1.34 1.34 0 0 1-2.68 0V9.62a1.2 1.2 0 0 0-.48-.96l-.9-.68a1.6 1.6 0 0 1-.62-1.03l-.42-2.6a1 1 0 0 1 1-1.15Z"
                  fill="white"
                />
              </svg>
            </div>
            <div className="absolute bottom-[52px] right-[38px] flex h-[50px] w-[50px] items-center justify-center rounded-full bg-black/30 backdrop-blur-sm">
              {/* Camera: body with a viewfinder bump and a lens */}
              <svg width="22" height="22" viewBox="0 0 22 22" fill="none">
                <path
                  d="M8.5 4.4h5l.9 1.8h3.1a2 2 0 0 1 2 2v7.4a2 2 0 0 1-2 2H4.5a2 2 0 0 1-2-2V8.2a2 2 0 0 1 2-2h3.1l.9-1.8Z"
                  fill="white"
                />
                <circle cx="11" cy="12" r="3.3" fill="#0b0f1a" />
                <circle cx="11" cy="12" r="2.1" fill="white" />
              </svg>
            </div>

            <div className="absolute bottom-[10px] left-1/2 h-[5px] w-[134px] -translate-x-1/2 rounded-full bg-white/85" />
          </div>
        </div>
      </div>
    </div>
  );
};
